INSERT INTO smart_search.departments (id, department_name) VALUES (5, '23 fgdfg');
INSERT INTO smart_search.departments (id, department_name) VALUES (11, 'Area 51');
INSERT INTO smart_search.departments (id, department_name) VALUES (15, 'Dep 34');
INSERT INTO smart_search.departments (id, department_name) VALUES (13, 'Dghg Hhjhk');
INSERT INTO smart_search.departments (id, department_name) VALUES (4, 'dsfdsfdsf');
INSERT INTO smart_search.departments (id, department_name) VALUES (8, 'fddffdsf');
INSERT INTO smart_search.departments (id, department_name) VALUES (12, 'fdfd ewrew');
INSERT INTO smart_search.departments (id, department_name) VALUES (14, 'Fek FGH');
INSERT INTO smart_search.departments (id, department_name) VALUES (19, 'NM');
INSERT INTO smart_search.departments (id, department_name) VALUES (17, 'Obre GHJhjk');
INSERT INTO smart_search.departments (id, department_name) VALUES (20, 'Rew Dep');
INSERT INTO smart_search.departments (id, department_name) VALUES (16, 'Rew FBNM');
INSERT INTO smart_search.departments (id, department_name) VALUES (6, 'Rhjhjkh');
INSERT INTO smart_search.departments (id, department_name) VALUES (10, 'Rrty 23');
INSERT INTO smart_search.departments (id, department_name) VALUES (2, 'rtuy_ghnm');
INSERT INTO smart_search.departments (id, department_name) VALUES (1, 'sdff_kkljj');
INSERT INTO smart_search.departments (id, department_name) VALUES (7, 'Twewerw');
INSERT INTO smart_search.departments (id, department_name) VALUES (9, 'Urtrty Thghjg');
INSERT INTO smart_search.departments (id, department_name) VALUES (18, 'VBNV');
INSERT INTO smart_search.departments (id, department_name) VALUES (3, 'wert_jkljlj');